### ISSUE TITLE
Setup pages and routing for the App

### ISSUE THREAD

**Issue by WawinyEdwin** [LL04-Finance-Dowell/100018-dowellWorkflowAi-testing#14]
Do the ground-up setup for the frontend team so they can focus on the design and creating components

--- We want to do this to reduce conflicts as the team grows and the application becomes more complex

**Comment by Josh-Ay** [comment]
Did the ground-up setup for routing as requested in this PR: https://github.com/LL04-Finance-Dowell/100018-dowellWorkflowAi-testing/pull/16
