### ISSUE TITLE
Errors and Success Message for Actions performed using snackbars

### ISSUE THREAD

**Issue by WawinyEdwin** [LL04-Finance-Dowell/100018-dowellWorkflowAi-testing#29]
I have tried to create a new document and my request has failed,
Possible reasons:

1.  My requests failed
2.  The data I submitted was not right.
3. My internet connection failed.

Give me feedback on those errors.

You  may also decide to give me success messages when an action was successfully done

**Comment by Josh-Ay** [comment]
Added in this commit: https://github.com/LL04-Finance-Dowell/100018-dowellWorkflowAi-testing/commit/d8b6a766a416654a42c31683eb369339e88f05c5
