### ISSUE TITLE
Title and Content Overlap

### ISSUE THREAD

**Issue by WawinyEdwin** [LL04-Finance-Dowell/100018-dowellWorkflowAi-testing#45]
We have content overlap that is bad for design remove it.
![Screenshot_20221202_085657](https://user-images.githubusercontent.com/58105928/205225214-3f1021d5-d140-40ce-a123-9e571f4bf61f.png)

**Comment by kule1163** [comment]
Is your mean boxes move with scrill ??

**Comment by WawinyEdwin** [comment]
Set workflow in Document title should be positioned top of the (Workflow,members) box as discussed yesterday

**Comment by kule1163** [comment]
Ok please look which design u sent me. U will see the same situation if u dont want i am going to fix it

**Comment by WawinyEdwin** [comment]
Just keep `set workflows in document` not to overlap when I scroll
![Screenshot_20221202_091324](https://user-images.githubusercontent.com/58105928/205227335-3144d747-9db0-4562-9ce3-7716ae6992c3.png)
Let it be like this always if I scroll

**Comment by kule1163** [comment]
Can i show u at meeting what is going on. Then decide its position please. I have to show u
