### ISSUE TITLE
Single Item pages for Workflow | Process | Template | Document

### ISSUE THREAD

**Issue by WawinyEdwin** [LL04-Finance-Dowell/100018-dowellWorkflowAi-testing#49]
Items in the above categories are increasingly becoming many, as our users are bound to create as many items as they want.
To enhance their experience of accessing the items. Make changes as per the requirement.

1. Build 
![image](https://user-images.githubusercontent.com/58105928/221535796-57aafbca-d682-4868-8991-5c05810f1549.png)
The items in the sidebar should point to a single page.

-  If I click drafts under templates then it should take me to a draft templates page
-  if I click saved process under Processes then it should take me to saved process page 

Please note that clicking every item in dropdown should take me to a page and not a section in an individual page.

**Comment by Josh-Ay** [comment]
This issue has been addressed in this commit: https://github.com/LL04-Finance-Dowell/100018-dowellWorkflowAi-testing/issues/49
